export default {
    ASSISTANT_LOADED: "ASSISTANT_LOADED",
    ASSISTANT_SELECTED: "ASSISTANT_SELECTED",
    STATS_LOADED: "STATS_LOADED",
    DATES_CHANGED: "DATES_CHANGED",
    UPDATE: "UPDATE",
    REFRESH_STATS: "REFRESH_STATS",
    baseURL: "<PASTE_BASE_URL_HERE>"
}